#shadow
shadow = true;            
no-dock-shadow = true;    
no-dnd-shadow = true;     
clear-shadow = true;      
      
#window
shadow-radius = 3;        
shadow-offset-x = -7;    
shadow-offset-y = -7;     
shadow-opacity = 0.7;    
shadow-exclude = [ "i:a:terminator", "_GTK_FRAME_EXTENTS@:c" ];
shadow-ignore-shaped = true; 

#opacity
menu-opacity = 0.9;    
inactive-opacity = 0.9;     
alpha-step = 0.06;      
inactive-dim = 0.1;    
blur-background-fixed = false;   
blur-background-exclude = [ "window_type = 'dock'", "window_type = 'desktop'" ];


#fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ "g:e:SMPlayer" ];

#other
backend = "xrender"
mark-wmwin-focused = true; 
mark-ovredir-focused = true; 
use-ewmh-active-win = false;  
detect-rounded-corners = true;
detect-client-opacity = true; 
refresh-rate = 0;   
vsync = "none"; 
dbe = false;     
paint-on-overlay = false; 
sw-opti = false; 
unredir-if-possible = false; 
focus-exclude = [ ];  
detect-transient = true; 
detect-client-leader = true; 
invert-color-include = [ ]; 
glx-swap-method = "undefined"; 

#window type settings
wintypes: {
        tooltip =  { fade = true; 
                shadow = false;
                opacity = 0.75;
                focus = true; 
        };
};

#opacity rules
opacity-rule = [ "70:class_g = 'i3bar'" ];
